module.exports = {
    mainController: require('./mainController'),
    projectsController: require('./projectsController'),
    usersController: require('./usersController'),
    manifestsController: require('./manifestsController'),
    companiesController: require('./companiesController'),
    packagesController: require('./packagesController'),
    cargosController: require('./cargosController'),
    pathsController: require('./pathsController'),
    packageArrivedController: require('./packageArrivedController'),
    registerController: require('./registerController'),
    adminController: require('./adminController'),
    qrController: require('./qrController'),
    locationsController: require('./locationsController'),
    imagesController: require('./imagesController'),
};
