###
POST http://{{host}}/{{api_prefix}}/manifests/3/cargos
Content-Type: application/json

{
  "name": "718",
  "model": "acm-1",
  "amount": 12,
  "creator": 1,
  "packageId": 7
}
###
GET http://{{host}}/{{api_prefix}}/manifests/1/cargos/6
Content-Type: application/json

###
DELETE http://{{host}}/{{api_prefix}}/manifests/1/cargos/9
Content-Type: application/json

###
GET http://{{host}}/{{api_prefix}}/manifests/1/cargos?limit=10&offset=0
Content-Type: application/json

###
GET http://{{host}}/{{api_prefix}}/cargos?name=79
Content-Type: application/json

###
