# List Manifests
GET http://{{host}}/{{api_prefix}}/manifests?limit=10&offset=0&noteNo=01
Content-Type: application/jsons

###

POST http://{{host}}/{{api_prefix}}/manifests
Content-Type: application/json

{
  "projectId": 1,
  "noteNo": "test002",
  "creator": 3,
  "receiver": 1
}

###

GET http://{{host}}/{{api_prefix}}/manifests/1
Content-Type: application/jsons

###

PATCH http://{{host}}/{{api_prefix}}/manifests/2
Content-Type: application/json

{
  "status": "SHIPPING"
}
###
