# Get arrivedinfo
GET http://{{host}}/{{api_prefix}}/packages/2/arrived-info
Content-Type: application/json

###
PATCH http://{{host}}/{{api_prefix}}/packages/2/arrived-info
Content-Type: application/json

{
  "pathNode": 1,
  "wayBillNo": "test111",
  "arrived": false
}
###
