# Get arrivedinfo
GET http://{{host}}/{{api_prefix}}/packages/3/arrived-info
Content-Type: application/json

###
PATCH http://{{host}}/{{api_prefix}}/packages/3/arrived-info
Content-Type: application/json

{
  "pathNode": 2,
  "arrived": true
}
###
