# Get paths
GET http://{{host}}/{{api_prefix}}/manifests/1/paths?packageId=1
Content-Type: application/json

###
# Create a path
POST http://{{host}}/{{api_prefix}}/manifests/1/paths
Content-Type: application/json

{
  "packageId": 1,
  "pathList": [{
    "waybillNo": "SF0001",
    "address": "内蒙古自治区",
    "assignee": 1,
    "arrived": true,
    "type": 0
  }, {
    "waybillNo": "SF0002",
    "address": "河南省",
    "assignee": 1,
    "arrived": false,
    "type": 2
  }, {
    "waybillNo": "SF0003",
    "address": "甘肃省",
    "assignee": 1,
    "arrived": false,
    "type": 1
  }]
}

###
PATCH http://{{host}}/{{api_prefix}}/manifests/1/paths
Content-Type: application/json

{
  "packageId": 1,
  "arrived": true,
  "pathIdList": [2,3]
}
