# Get paths
GET http://{{host}}/{{api_prefix}}/manifests/1/paths
Content-Type: application/json

###
# Create a path
POST http://{{host}}/{{api_prefix}}/manifests/2/paths
Content-Type: application/json

[{
  "address": "内蒙古自治区",
  "assignee": 1,
  "type": 0
}, {
  "address": "河南省",
  "assignee": 1,
  "type": 2
}, {
  "address": "甘肃省",
  "assignee": 1,
  "type": 1
}]

###
PUT http://{{host}}/{{api_prefix}}/manifests/1/paths/1
Content-Type: application/json

[{
  "address": "内蒙古自治区",
  "assignee": 1,
  "type": 0
}, {
  "address": "河南省",
  "assignee": 1,
  "type": 2
}, {
  "address": "河北省",
  "assignee": 1,
  "type": 2
}, {
  "address": "甘肃省",
  "assignee": 1,
  "type": 1
}]
