# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
# Create a Project
POST http://{{host}}/{{api_prefix}}/projects
Content-Type: application/json

{
  "name": "testprj1",
  "ownerId": 2,
  "receiverId": 3,
  "status": "ACTIVE"
}

###
# List Projects
GET http://{{host}}/{{api_prefix}}/projects?limit=10&offset=0
Content-Type: application/jsons

###
# Get Projects
GET http://{{host}}/{{api_prefix}}/projects/10
Content-Type: application/json

###
# Update Projects
PATCH http://{{host}}/{{api_prefix}}/projects/1
Content-Type: application/json

{
  "receiverId": 3,
  "status": "COMPLETED"
}

###
# Delete a project
DELETE http://{{host}}/{{api_prefix}}/projects/3
Content-Type: application/json

###

GET http://{{host}}/{{api_prefix}}/projects/1/users
Content-Type: application/json

###

POST http://{{host}}/{{api_prefix}}/projects/1/users/3
Content-Type: application/json

{
  "projectRole": "Project Admin"
}

###

# QR code
POST http://{{host}}/{{api_prefix}}/qrcode
Content-Type: application/json

{
  "content": "test"
}

###
