# Get captcha
GET http://{{host}}/{{api_prefix}}/captcha
Content-Type: application/svg+xml

###
GET http://{{host}}/{{api_prefix}}/captcha?base64=true
Content-Type: application/json

###
POST http://{{host}}/{{api_prefix}}/user?action=login
Content-Type: application/json

{
  "userId": "13564536791",
  "password": "User0",
  "captcha": "yeZa"
}

###
POST http://{{host}}/{{api_prefix}}/user?action=logout
Content-Type: application/json

{
  "userId": "13564536792"
}

###
PATCH http://{{host}}/{{api_prefix}}/user/13600000000
Content-Type: application/json

{
  "oldPassword": "User4",
  "newPassword": "User0"
}
