# Create a User
POST http://{{host}}/{{api_prefix}}/users
Content-Type: application/json

{
  "name": "testUser",
  "title": "CEO",
  "identity": "45678910123",
  "phone": "13600000001",
  "email": "test@163.com"
}

###
# Get a user
GET http://{{host}}/{{api_prefix}}/users/1
Content-Type: application/json

# List users
###
GET http://{{host}}/{{api_prefix}}/users?limit=10&offset=0&company=6
Content-Type: application/json

###
